export const CARTDATACONSTANT = "CARTDATACONSTANT";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_ITEM = "INCREMENT_ITEM";

export const DECREMENT_ITEM = "DECREMENT_ITEM";
